-- ============================================================
--  ARQUIVO APOSENTADO — não use.
--
--  Este arquivo descrevia apenas as 4 tabelas originais e ficou
--  para trás quando o catálogo de exercícios (exercises /
--  plan_exercises) foi criado direto pelo SQL Editor. Rodá-lo
--  hoje monta um banco que o app NÃO consegue usar.
--
--  O schema agora vive versionado e numerado em:
--
--      supabase/migrations/001_initial.sql
--      supabase/migrations/002_catalog.sql
--      supabase/migrations/003_volume.sql
--
--  Rode-os NA ORDEM no SQL Editor. Todos são idempotentes:
--  seguro rodar de novo em banco existente.
-- ============================================================